export const NIGERIAN_STATES: Record<string, string[]> = {
  Abia:          ["Aba", "Umuahia", "Ohafia", "Arochukwu"],
  Adamawa:       ["Yola", "Mubi", "Jimeta", "Ngurore"],
  "Akwa Ibom":   ["Uyo", "Eket", "Ikot Ekpene", "Oron"],
  Anambra:       ["Awka", "Onitsha", "Nnewi", "Ekwulobia"],
  Bauchi:        ["Bauchi", "Azare", "Misau", "Jama'are"],
  Bayelsa:       ["Yenagoa", "Ogbia", "Brass", "Sagbama"],
  Benue:         ["Makurdi", "Gboko", "Katsina-Ala", "Otukpo"],
  Borno:         ["Maiduguri", "Biu", "Gubio", "Monguno"],
  "Cross River":  ["Calabar", "Ogoja", "Ikom", "Obudu"],
  Delta:         ["Asaba", "Warri", "Sapele", "Ughelli"],
  Ebonyi:        ["Abakaliki", "Afikpo", "Onueke", "Ezzamgbo"],
  Edo:           ["Benin City", "Auchi", "Uromi", "Ekpoma"],
  Ekiti:         ["Ado-Ekiti", "Ikere", "Oye", "Ijero"],
  Enugu:         ["Enugu", "Nsukka", "Agbani", "Oji River"],
  FCT:           ["Abuja", "Gwagwalada", "Kuje", "Bwari", "Kwali", "Abaji"],
  Gombe:         ["Gombe", "Deba", "Kaltungo", "Billiri"],
  Imo:           ["Owerri", "Orlu", "Okigwe", "Mbaise"],
  Jigawa:        ["Dutse", "Hadejia", "Gumel", "Kazaure"],
  Kaduna:        ["Kaduna", "Zaria", "Kafanchan", "Kagoro"],
  Kano:          ["Kano", "Wudil", "Bichi", "Rano"],
  Katsina:       ["Katsina", "Daura", "Funtua", "Mashi"],
  Kebbi:         ["Birnin Kebbi", "Argungu", "Yelwa", "Kamba"],
  Kogi:          ["Lokoja", "Okene", "Kabba", "Idah"],
  Kwara:         ["Ilorin", "Offa", "Omu-Aran", "Lafiagi"],
  Lagos:         ["Ikeja", "Lagos Island", "Victoria Island", "Lekki", "Ajah", "Surulere", "Yaba", "Mushin", "Isolo", "Ikorodu", "Agege", "Alimosho", "Badagry", "Epe"],
  Nasarawa:      ["Lafia", "Keffi", "Akwanga", "Nasarawa"],
  Niger:         ["Minna", "Bida", "Suleja", "Kontagora"],
  Ogun:          ["Abeokuta", "Sagamu", "Ijebu-Ode", "Ilaro"],
  Ondo:          ["Akure", "Ondo", "Owo", "Ikare"],
  Osun:          ["Osogbo", "Ile-Ife", "Ilesa", "Ede"],
  Oyo:           ["Ibadan", "Ogbomoso", "Oyo", "Iseyin"],
  Plateau:       ["Jos", "Bukuru", "Shendam", "Pankshin"],
  Rivers:        ["Port Harcourt", "Obio-Akpor", "Eleme", "Bonny"],
  Sokoto:        ["Sokoto", "Tambuwal", "Wurno", "Illela"],
  Taraba:        ["Jalingo", "Wukari", "Bali", "Zing"],
  Yobe:          ["Damaturu", "Potiskum", "Nguru", "Gashua"],
  Zamfara:       ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka"],
};

export const NIGERIAN_STATE_NAMES = Object.keys(NIGERIAN_STATES).sort();